// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 17/3/2026, 6:07:47 pm
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/user1/Desktop/Nuxt/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user1/Desktop/Nuxt/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user1/Desktop/Nuxt/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user1/Desktop/Nuxt/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user1/Desktop/Nuxt/app/plugins/**/*.{js,ts,mjs}","C:/Users/user1/Desktop/Nuxt/app/composables/**/*.{js,ts,mjs}","C:/Users/user1/Desktop/Nuxt/app/utils/**/*.{js,ts,mjs}","C:/Users/user1/Desktop/Nuxt/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user1/Desktop/Nuxt/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user1/Desktop/Nuxt/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user1/Desktop/Nuxt/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;